Repository Favor-Gift-Reminder/Favor-iOS, pull requests merged in 2023-05, with the labels that each got.

#121 [Feat] 선물 등록 친구 선택 페이지 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/NewGiftFlow.swift
  Favor/Favor/Sources/Scenes/Gift/NewGiftFriendSection.swift
  Favor/Favor/Sources/Scenes/Gift/Reactors/CellReactros/NewGiftFriendCellReactor.swift
  Favor/Favor/Sources/Scenes/Gift/Reactors/NewGiftFriendHeaderViewReactor.swift
  Favor/Favor/Sources/Scenes/Gift/Reactors/NewGiftFriendViewReactor.swift
  Favor/Favor/Sources/Scenes/Gift/Reactors/NewGiftViewReactor.swift
  Favor/Favor/Sources/Scenes/Gift/ViewControllers/NewGiftFriendVC.swift
  Favor/Favor/Sources/Scenes/Gift/ViewControllers/NewGiftVC.swift
  Favor/Favor/Sources/Scenes/Gift/Views/Cells/NewGiftFriendCell.swift
  Favor/Favor/Sources/Scenes/Gift/Views/Cells/NewGiftFriendEmptyCell.swift
  Favor/Favor/Sources/Scenes/Gift/Views/NewGiftFriendFooterView.swift
  Favor/Favor/Sources/Scenes/Gift/Views/NewGiftFriendHeaderView.swift
  Favor/Favor/Sources/Scenes/Home/Reactors/HomeViewReactor.swift
  Favor/Favor/Sources/Scenes/Home/ViewControllers/HomeVC.swift
  Favor/Favor/Sources/Scenes/Home/Views/HomeHeaderView.swift
  Favor/FavorKit/Sources/FavorKit/Base/BaseCardCell.swift
  Favor/FavorKit/Sources/FavorKit/Base/BaseFriendCell.swift
Labels: 🎨 UI

#126 [Feat] 친구 페이지 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Sources/Flows/AnniversaryListFlow.swift
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/FriendListFlow.swift
  Favor/Favor/Sources/Flows/MyPageFlow.swift
  Favor/Favor/Sources/Scenes/AnniversaryList/AnniversaryListSection.swift
  Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/AnniversaryListViewReactor.swift
  Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/CellReactors/AnniversaryListCellReactor.swift
  Favor/Favor/Sources/Scenes/AnniversaryList/ViewControllers/AnniversaryListVC.swift
  Favor/Favor/Sources/Scenes/AnniversaryList/Views/AnniversaryListSectionHeaderView.swift
  Favor/Favor/Sources/Scenes/AnniversaryList/Views/Cells/AnniversaryListCell.swift
  Favor/Favor/Sources/Scenes/FriendList/FriendListSection.swift
  Favor/Favor/Sources/Scenes/FriendList/Reactors/BaseFriendReactor.swift
  Favor/Favor/Sources/Scenes/FriendList/Reactors/EditFriendViewReactor.swift
  Favor/Favor/Sources/Scenes/FriendList/Reactors/FriendListViewReactor.swift
  Favor/Favor/Sources/Scenes/FriendList/ViewControllers/BaseFriendVC.swift
  Favor/Favor/Sources/Scenes/FriendList/ViewControllers/EditFriendVC.swift
  Favor/Favor/Sources/Scenes/FriendList/ViewControllers/FriendListVC.swift
  Favor/Favor/Sources/Scenes/FriendList/Views/Cells/EditFriendCell.swift
  Favor/Favor/Sources/Scenes/FriendList/Views/Cells/FriendListCell.swift
  Favor/Favor/Sources/Scenes/FriendList/Views/EditFriendCollectionHeaderView.swift
  Favor/Favor/Sources/Scenes/FriendList/Views/FriendListSectionHeader.swift
  Favor/Favor/Sources/Scenes/Gift/NewGiftFriendSection.swift
  Favor/Favor/Sources/Scenes/Gift/Reactors/CellReactros/NewGiftFriendCellReactor.swift
  Favor/Favor/Sources/Scenes/Gift/Reactors/NewGiftFriendViewReactor.swift
  Favor/Favor/Sources/Scenes/Gift/Views/Cells/NewGiftFriendCell.swift
  Favor/Favor/Sources/Scenes/Home/Reactors/HomeViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/Common/Reactors/CellReactors/ProfileFriendCellReactor.swift
  Favor/Favor/Sources/Scenes/Profile/Common/ViewControllers/BaseProfileVC.swift
  Favor/Favor/Sources/Scenes/Profile/Common/Views/Cells/ProfileFriendCell.swift
  Favor/Favor/Sources/Scenes/Profile/EditMyPage/EditMyPageSection.swift
  Favor/Favor/Sources/Scenes/Profile/Friend/FriendSection.swift
  Favor/Favor/Sources/Scenes/Profile/Friend/Reactors/CellReactors/FriendCellReactor.swift
  Favor/Favor/Sources/Scenes/Profile/Friend/Reactors/FriendSectionCollectionHeaderReactor.swift
  Favor/Favor/Sources/Scenes/Profile/Friend/Reactors/FriendViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/Friend/ViewControllers/FriendVC.swift
  Favor/Favor/Sources/Scenes/Profile/Friend/Views/Cells/FriendCell.swift
  Favor/Favor/Sources/Scenes/Profile/Friend/Views/FriendSectionCollectionHeader.swift
  Favor/Favor/Sources/Scenes/Profile/MyPage/Reactors/MyPageViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/MyPage/ViewControllers/MyPageVC.swift
  Favor/Favor/Sources/Scenes/Profile/ProfileSection.swift
  Favor/Favor/Sources/Scenes/Reminder/Reactor/ReminderViewReactor.swift
  Favor/FavorKit/Sources/FavorKit/Base/BaseCardCell.swift
  Favor/FavorKit/Sources/FavorKit/Base/BaseCollectionViewCell.swift
  Favor/FavorKit/Sources/FavorKit/Base/BaseFriendCell.swift
  Favor/FavorKit/Sources/FavorKit/Components/CollectionView/Cells/Protocols/UICollectionViewCell+GestureInteractable.swift
  Favor/FavorKit/Sources/FavorKit/Components/CollectionView/Cells/Protocols/UICollectionViewCell+Pressable.swift
  Favor/FavorKit/Sources/FavorKit/Components/CollectionView/Cells/Protocols/UICollectionViewCell+Tappable.swift
  Favor/FavorKit/Sources/FavorKit/Components/CollectionView/FavorCompositionalLayout.swift
  Favor/FavorKit/Sources/FavorKit/Extensions/Results+.swift
  Favor/FavorKit/Sources/FavorKit/Managers/RealmManager.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/Fetcher.swift
Labels: ✨ New Feature, ♻️ Refactoring, 🎨 UI

#130 [Feat] 새 친구 등록 / 친구 프로필 수정 페이지 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Favor/Favor/Assets/FavorProfileImageView.swift
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/FriendFlow.swift
  Favor/Favor/Sources/Flows/NewGiftFlow.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/SetProfileVC.swift
  Favor/Favor/Sources/Scenes/BottomSheet/FilterBottomSheet.swift
  Favor/Favor/Sources/Scenes/Friend/Reactors/FriendManagementViewReactor.swift
  Favor/Favor/Sources/Scenes/Friend/ViewControllers/FriendManagementVC.swift
  Favor/Favor/Sources/Scenes/FriendList/ViewControllers/EditFriendVC.swift
  Favor/Favor/Sources/Scenes/Gift/Reactors/NewGiftFriendViewReactor.swift
  Favor/Favor/Sources/Scenes/Gift/ViewControllers/NewGiftFriendVC.swift
  Favor/Favor/Sources/Scenes/Gift/Views/Cells/NewGiftFriendCell.swift
  Favor/Favor/Sources/Scenes/Gift/Views/NewGiftFriendFooterView.swift
  Favor/Favor/Sources/Scenes/Profile/Common/Views/Cells/ProfileFriendCell.swift
  Favor/Favor/Sources/Scenes/Profile/Common/Views/ProfileView.swift
  Favor/FavorKit/Sources/FavorKit/Base/BaseFriendCell.swift
  Favor/FavorKit/Sources/FavorKit/Components/CollectionView/FavorCompositionalLayout.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorIconImageView.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorProfileImageView.swift
Labels: 🎨 UI

#139 [Refactor] 홈 리팩토링
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Sources/Scenes/Gift/VIewControllers/GiftVC.swift
  Favor/Favor/Sources/Scenes/Gift/ViewControllers/GiftVC.swift
  Favor/Favor/Sources/Scenes/Home/HomeSection.swift
  Favor/Favor/Sources/Scenes/Home/Reactors/CellReactors/TimelineCellReactor.swift
  Favor/Favor/Sources/Scenes/Home/Reactors/CellReactors/UpcomingCellReactor.swift
  Favor/Favor/Sources/Scenes/Home/Reactors/HeaderViewReactor.swift
  Favor/Favor/Sources/Scenes/Home/Reactors/HomeViewReactor.swift
  Favor/Favor/Sources/Scenes/Home/ViewControllers/HomeVC.swift
  Favor/Favor/Sources/Scenes/Home/Views/Cells/HomeTimelineCell.swift
  Favor/Favor/Sources/Scenes/Home/Views/Cells/HomeUpcomingCell.swift
  Favor/Favor/Sources/Scenes/Home/Views/HomeHeaderView.swift
  Favor/Favor/Sources/Scenes/Reminder/Reactor/ReminderViewReactor.swift
  Favor/FavorKit/Sources/FavorKit/Base/BaseBottomSheet.swift
  Favor/FavorKit/Sources/FavorKit/Components/CollectionView/Cells/FavorEmptyCell.swift
  Favor/FavorKit/Sources/FavorKit/Components/CollectionView/FavorCompositionalLayout.swift
  Favor/FavorKit/Sources/FavorKit/Components/CollectionView/Items/FavorLoadingFooterView.swift
  Favor/FavorKit/Sources/FavorKit/Constants/AnniversaryCategory.swift
  Favor/FavorKit/Sources/FavorKit/Constants/GiftFilterType.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/Gift.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/Reminder.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/DataMapping/ResponseDTO/ReminderResponseDTO.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/Fetcher.swift
Labels: ♻️ Refactoring

#145 [Feat] 종류별 팝업 창 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Scenes/Popup/AlertPopup.swift
  Favor/Favor/Sources/Scenes/Popup/BasePopup.swift
  Favor/Favor/Sources/Scenes/Popup/ReminderDatePopup.swift
Labels: 🎨 UI
