Repository Favor-Gift-Reminder/Favor-iOS, pull requests merged in 2023-02, with the labels that each got.

#49 [Feat] FTUXStorage 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Configuration/Protocols/BaseView.swift
  Favor/Favor/Configuration/Protocols/Coordinator.swift
  Favor/Favor/Configuration/Protocols/ReuseIdentifying.swift
  Favor/Favor/Sources/Scenes/Application/SceneDelegate.swift
  Favor/Favor/Sources/Storages/FTUXStorage.swift
  Favor/Favor/Sources/Utils/CoreGraphicManager.swift
  Favor/Favor/Sources/Utils/PHPickerManager.swift
  Favor/Favor/Sources/Utils/UpdateHandlerManager.swift
  Favor/Favor/Sources/Utils/ValidateManager.swift
  Favor/Favor/Sources/Views/FavorTextField.swift
  Favor/Favor/Sources/Views/LargeFavorButton.swift
  Favor/Favor/Sources/Views/PlainFavorButton.swift
  Favor/Favor/Sources/Views/SmallFavorButton.swift
Labels: ✨ New Feature

#50 FAVOR-55/Refactor/RxFlow
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Configuration/Base/BaseCoordinator.swift
  Favor/Favor/Configuration/Base/Delegate/CoordinatorFinishDelegate.swift
  Favor/Favor/Sources/Flows/AppFlow.swift
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/AppStepper.swift
  Favor/Favor/Sources/Flows/AppStpper.swift
  Favor/Favor/Sources/Flows/AuthFlow.swift
  Favor/Favor/Sources/Flows/OnboardingFlow.swift
  Favor/Favor/Sources/Flows/TabBarFlow.swift
  Favor/Favor/Sources/Scenes/Application/Flows/AppFlow.swift
  Favor/Favor/Sources/Scenes/Application/Flows/AppStep.swift
  Favor/Favor/Sources/Scenes/Application/Flows/AppStepper.swift
  Favor/Favor/Sources/Scenes/Application/SceneDelegate.swift
  Favor/Favor/Sources/Scenes/Application/TabBar/TabBarCoordinator.swift
  Favor/Favor/Sources/Scenes/Auth/Flows/AuthFlow.swift
  Favor/Favor/Sources/Scenes/Auth/Flows/AuthStep.swift
  Favor/Favor/Sources/Scenes/Auth/Reactor/SelectSignInReactor.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/SetProfileVC.swift
  Favor/Favor/Sources/Scenes/Home/Home/Coordinator/HomeCoordinator.swift
  Favor/Favor/Sources/Scenes/Home/Home/Reactor/HomeReactor.swift
  Favor/Favor/Sources/Scenes/Home/Home/ViewControllers/HomeVC.swift
  Favor/Favor/Sources/Scenes/Home/NewGift/Coordinator/NewGiftCoordinator.swift
  Favor/Favor/Sources/Scenes/Home/Search/Coordinator/SearchCoordinator.swift
  Favor/Favor/Sources/Scenes/MyPage/Coordinator/MyPageCoordinator.swift
  Favor/Favor/Sources/Scenes/Onboarding/OnboardingVC.swift
  Favor/Favor/Sources/Scenes/Reminder/Coordinator/ReminderCoordinator.swift
  Favor/Favor/Sources/Scenes/Splash/SplashVC.swift
Labels: ♻️ Refactoring

#52 [Test] TestFlow 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Sources/Flows/AppFlow.swift
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/AppStepper.swift
  Favor/Favor/Sources/Flows/AppStpper.swift
  Favor/Favor/Sources/Flows/HomeFlow.swift
  Favor/Favor/Sources/Scenes/Home/Home/Flows/HomeStep.swift
Labels: ✨ New Feature

#55 Favor 65/feat/home empty cell
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Sources/Scenes/Home/Home/Reactor/HeaderReactor.swift
  Favor/Favor/Sources/Scenes/Home/Home/Reactor/HomeReactor.swift
  Favor/Favor/Sources/Scenes/Home/Home/ViewControllers/HomeVC.swift
  Favor/Favor/Sources/Scenes/Home/Home/Views/HeaderView.swift
  Favor/Favor/Sources/Scenes/Home/Home/Views/HomeSection.swift
  Favor/Favor/Sources/Scenes/Home/Home/Views/UpcomingSection.swift
  Favor/Favor/Sources/Views/EmptyCollectionViewCell.swift
Labels: 🎨 UI

#57 [Feat] SearchUI
  .gitignore
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  Favor/Favor.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Favor/Favor/Configuration/Extensions/String+.swift
  Favor/Favor/Sources/Flows/AppFlow.swift
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/SearchFlow.swift
  Favor/Favor/Sources/Scenes/Home/Search/Reactor/SearchReactor.swift
  Favor/Favor/Sources/Scenes/Home/Search/Reactor/SearchResultReactor.swift
  Favor/Favor/Sources/Scenes/Home/Search/ViewControllers/.gitkeep
  Favor/Favor/Sources/Scenes/Home/Search/ViewControllers/SearchResultVC.swift
  Favor/Favor/Sources/Scenes/Home/Search/ViewControllers/SearchVC.swift
  Favor/Favor/Sources/Views/FavorSearchBar.swift
Labels: 🎨 UI

#59 [Feat] 머지되지 않은 EmptyCell 복구
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Sources/Scenes/Home/Home/Reactor/HeaderReactor.swift
  Favor/Favor/Sources/Scenes/Home/Home/Reactor/HomeReactor.swift
  Favor/Favor/Sources/Scenes/Home/Home/ViewControllers/HomeVC.swift
  Favor/Favor/Sources/Scenes/Home/Home/Views/HeaderView.swift
  Favor/Favor/Sources/Scenes/Home/Home/Views/HomeSection.swift
  Favor/Favor/Sources/Scenes/Home/Home/Views/UpcomingSection.swift
  Favor/Favor/Sources/Views/EmptyCollectionViewCell.swift
Labels: 🏎️ Fetch

#64 [Refactor] FavorTextField 리팩토링
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Configuration/Assets/Assets.xcassets/MyPageHeaderPlaceholder.imageset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/MyPageHeaderPlaceholder.imageset/placeholder.png
  Favor/Favor/Configuration/Constants/.gitkeep
  Favor/Favor/Configuration/Extensions/Constants.swift
  Favor/Favor/Configuration/Extensions/UIView+.swift
  Favor/Favor/Sources/Flows/AppFlow.swift
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/AppStpper.swift
  Favor/Favor/Sources/Flows/MyPageFlow.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/SetProfileVC.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/SignInVC.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/SignUpVC.swift
  Favor/Favor/Sources/Scenes/MyPage/Edit/Reactor/EditMyPageReactor.swift
  Favor/Favor/Sources/Scenes/MyPage/Edit/ViewControllers/EditMyPageVC.swift
  Favor/Favor/Sources/Scenes/MyPage/Reactor/.gitkeep
  Favor/Favor/Sources/Scenes/MyPage/Reactor/CollectionViewCellReactors/AnniversaryCellReactor.swift
  Favor/Favor/Sources/Scenes/MyPage/Reactor/CollectionViewCellReactors/FavorCellReactor.swift
  Favor/Favor/Sources/Scenes/MyPage/Reactor/CollectionViewCellReactors/FriendCellReactor.swift
  Favor/Favor/Sources/Scenes/MyPage/Reactor/CollectionViewCellReactors/GiftStatCellReactor.swift
  Favor/Favor/Sources/Scenes/MyPage/Reactor/CollectionViewCellReactors/NewProfileCellReactor.swift
  Favor/Favor/Sources/Scenes/MyPage/Reactor/MyPageHeaderReactor.swift
  Favor/Favor/Sources/Scenes/MyPage/Reactor/MyPageReactor.swift
  Favor/Favor/Sources/Scenes/MyPage/Reactor/MyPageSectionHeaderReactor.swift
  Favor/Favor/Sources/Scenes/MyPage/ViewControllers/MyPageVC.swift
  Favor/Favor/Sources/Scenes/MyPage/Views/.gitkeep
  Favor/Favor/Sources/Scenes/MyPage/Views/BackgroundView.swift
  Favor/Favor/Sources/Scenes/MyPage/Views/CollectionViewCells/AnniversaryCell.swift
  Favor/Favor/Sources/Scenes/MyPage/Views/CollectionViewCells/FavorCell.swift
  Favor/Favor/Sources/Scenes/MyPage/Views/CollectionViewCells/FriendCell.swift
  Favor/Favor/Sources/Scenes/MyPage/Views/CollectionViewCells/GiftStatCell.swift
  Favor/Favor/Sources/Scenes/MyPage/Views/CollectionViewCells/NewProfileCell.swift
  Favor/Favor/Sources/Scenes/MyPage/Views/MyPageHeaderView.swift
  Favor/Favor/Sources/Scenes/MyPage/Views/MyPageSection.swift
  Favor/Favor/Sources/Scenes/MyPage/Views/MyPageSectionHeaderView.swift
  Favor/Favor/Sources/Views/EmptyCollectionViewCell.swift
  Favor/Favor/Sources/Views/FavorTextField.swift
  Favor/Favor/Sources/Views/OldFavorTextField.swift
Labels: ♻️ Refactoring

#68 [Feat] Reusable 설치 & MyPage에 적용
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Favor/Favor/Sources/Scenes/Common/Views/Cells/FavorAnniversaryCell.swift
  Favor/Favor/Sources/Scenes/Common/Views/Cells/FavorGiftStatsCell.swift
  Favor/Favor/Sources/Scenes/Common/Views/Cells/FavorPrefersCell.swift
  Favor/Favor/Sources/Scenes/Common/Views/Cells/FavorSetupProfileCell.swift
  Favor/Favor/Sources/Scenes/MyPage/ViewControllers/EditMyPageVC.swift
  Favor/Favor/Sources/Scenes/MyPage/ViewControllers/MyPageVC.swift
  Favor/Favor/Sources/Scenes/MyPage/Views/Cells/FriendCell.swift
  Favor/Favor/Sources/Scenes/MyPage/Views/Cells/NewAnniversaryHeaderView.swift
  Favor/Favor/Sources/Scenes/MyPage/Views/MyPageSectionFooterView.swift
  Favor/Favor/Sources/Scenes/MyPage/Views/MyPageSectionHeaderView.swift
Labels: 🛠️ Project Setup

#70 [Feat] Realm & RxRealm 설치
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Favor/Favor/Sources/Scenes/Application/AppDelegate.swift
Labels: 🛠️ Project Setup

#73 [Feat] OnboardingUI 구현 및 개편
  Favor/Favor/Configuration/Base/BaseViewController.swift
  Favor/Favor/Sources/Scenes/Onboarding/OnboardingCell.swift
  Favor/Favor/Sources/Scenes/Onboarding/OnboardingSlide.swift
  Favor/Favor/Sources/Scenes/Onboarding/OnboardingVC.swift
Labels: 🎨 UI
