Repository Favor-Gift-Reminder/Favor-iOS, pull requests merged in 2023-04, with the labels that each got.

#104 [Feat] SearchFlow 구현 연기
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/HomeFlow.swift
  Favor/Favor/Sources/Flows/SearchFlow.swift
  Favor/Favor/Sources/Scenes/Home/Reactors/HomeViewReactor.swift
  Favor/Favor/Sources/Scenes/Home/Views/HeaderView.swift
  Favor/Favor/Sources/Scenes/Search/Reactors/SearchViewReactor.swift
  Favor/Favor/Sources/Scenes/Search/ViewControllers/SearchVC.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorSearchBar.swift
Labels: 🏎️ Fetch

#102 [Feat] AddGift UI 구현 및 GiftFlow 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Assets/Assets.xcassets/Icon/ic_photo.imageset/Contents.json
  Favor/Favor/Assets/Assets.xcassets/Icon/ic_photo.imageset/Subtract.png
  Favor/Favor/Assets/Assets.xcassets/Icon/ic_photo.imageset/Subtract@2x.png
  Favor/Favor/Assets/Assets.xcassets/Icon/ic_photo.imageset/Subtract@3x.png
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/GiftFlow.swift
  Favor/Favor/Sources/Flows/HomeFlow.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/Password/NewPasswordVC.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/SignUpVC.swift
  Favor/Favor/Sources/Scenes/Gift/NewGiftPhotoSection.swift
  Favor/Favor/Sources/Scenes/Gift/PickedPictureSection.swift
  Favor/Favor/Sources/Scenes/Gift/Reactors/NewGiftViewReactor.swift
  Favor/Favor/Sources/Scenes/Gift/Reactors/PickPictureCellReactor.swift
  Favor/Favor/Sources/Scenes/Gift/Reactors/PickedPictureCellReactor.swift
  Favor/Favor/Sources/Scenes/Gift/ViewControllers/NewGiftVC.swift
  Favor/Favor/Sources/Scenes/Gift/Views/Cells/NewGiftEmptyCell.swift
  Favor/Favor/Sources/Scenes/Gift/Views/Cells/NewGiftPhotoCell.swift
  Favor/Favor/Sources/Scenes/Gift/Views/NewGiftChoiceFriendButton.swift
  Favor/Favor/Sources/Scenes/Gift/Views/PickPictureCell.swift
  Favor/Favor/Sources/Scenes/Gift/Views/PickedPictureCell.swift
  Favor/Favor/Sources/Scenes/Home/Reactors/HomeViewReactor.swift
  Favor/Favor/Sources/Scenes/NewGift/ViewControllers/.gitkeep
  Favor/Favor/Sources/Scenes/Onboarding/OnboardingVC.swift
  Favor/Favor/Sources/Scenes/Search/ViewControllers/SearchVC.swift
  Favor/FavorKit/Sources/FavorKit/Base/BaseNavigationController.swift
  Favor/FavorKit/Sources/FavorKit/Components/Button/FavorLargeButton.swift
  Favor/FavorKit/Sources/FavorKit/Components/Button/FavorPlainButton.swift
  Favor/FavorKit/Sources/FavorKit/Components/Button/FavorSmallButton.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorCategoryView.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorDatePickerTextField.swift
  Favor/FavorKit/Sources/FavorKit/Constants/ButtonType/FavorLargeButtonType.swift
  Favor/FavorKit/Sources/FavorKit/Constants/ButtonType/FavorPlainButtonType.swift
  Favor/FavorKit/Sources/FavorKit/Constants/ButtonType/FavorSmallButtonType.swift
  Favor/FavorKit/Sources/FavorKit/Constants/FavorCategory.swift
  Favor/FavorKit/Sources/FavorKit/Extensions/UIImage+.swift
  Favor/FavorKit/Sources/FavorKit/Managers/PHPickerManager.swift
Labels: 🎨 UI

#107 [Feat] BottomSheet 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Sources/Deprecated/BaseBottomSheetViewController.swift
  Favor/Favor/Sources/Deprecated/FilterVC.swift
  Favor/Favor/Sources/Flows/HomeFlow.swift
  Favor/Favor/Sources/Scenes/FilterBottomSheet.swift
  Favor/FavorKit/Sources/FavorKit/Base/BaseBottomSheet.swift
Labels: 🎨 UI

#115 [Feat] SearchFlow 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Sources/Flows/AppFlow.swift
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/SearchFlow.swift
  Favor/Favor/Sources/Models/ReminderEditor.swift
  Favor/Favor/Sources/Scenes/Home/Reactors/CellReactors/TimelineCellReactor.swift
  Favor/Favor/Sources/Scenes/Home/Reactors/CellReactors/UpcomingCellReactor.swift
  Favor/Favor/Sources/Scenes/Home/ViewControllers/HomeVC.swift
  Favor/Favor/Sources/Scenes/Reminder/Reactor/ReminderCellReactor.swift
  Favor/Favor/Sources/Scenes/Reminder/Reactor/ReminderDetailViewReactor.swift
  Favor/Favor/Sources/Scenes/Search/Reactors/CellReactors/SearchGiftResultCellReactor.swift
  Favor/Favor/Sources/Scenes/Search/Reactors/CellReactors/SearchUserResultCellReactor.swift
  Favor/Favor/Sources/Scenes/Search/Reactors/SearchResultViewReactor.swift
  Favor/Favor/Sources/Scenes/Search/Reactors/SearchViewReactor.swift
  Favor/Favor/Sources/Scenes/Search/SearchRecentSection.swift
  Favor/Favor/Sources/Scenes/Search/SearchResultSection.swift
  Favor/Favor/Sources/Scenes/Search/ViewControllers/BaseSearchVC.swift
  Favor/Favor/Sources/Scenes/Search/ViewControllers/SearchResultVC.swift
  Favor/Favor/Sources/Scenes/Search/ViewControllers/SearchVC.swift
  Favor/Favor/Sources/Scenes/Search/Views/Cells/SearchGiftResultCell.swift
  Favor/Favor/Sources/Scenes/Search/Views/Cells/SearchRecentCell.swift
  Favor/Favor/Sources/Scenes/Search/Views/Cells/SearchUserResultCell.swift
  Favor/Favor/Sources/Scenes/Search/Views/SearchRecentHeader.swift
  Favor/Favor/Sources/Scenes/Search/Views/SelectedIndicatorBar.swift
  Favor/FavorKit/Sources/FavorKit/Base/BaseNavigationController.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorSearchBar.swift
  Favor/FavorKit/Sources/FavorKit/Constants/ButtonType/FavorLargeButtonType.swift
  Favor/FavorKit/Sources/FavorKit/Extensions/Date+.swift
  Favor/FavorKit/Sources/FavorKit/Managers/RealmManager.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/Friend.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/Gift.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/Photo.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/Reminder.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/User.swift
  Favor/FavorKit/Sources/FavorKit/Models/SearchRecent.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/Fetcher.swift
Labels: ♻️ Refactoring, 🎨 UI

#119 [Feat] 회원가입 네트워킹 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Assets/Assets.xcassets/Favor_TypoLogo.imageset/Contents.json
  Favor/Favor/Assets/Assets.xcassets/Favor_TypoLogo.imageset/Group 26086499.png
  Favor/Favor/Assets/Assets.xcassets/Favor_TypoLogo.imageset/Group 26086500.png
  Favor/Favor/Assets/Assets.xcassets/Favor_TypoLogo.imageset/Group 26086501.png
  Favor/Favor/Sources/Flows/AppFlow.swift
  Favor/Favor/Sources/Scenes/Auth/Reactors/SetProfileViewReactor.swift
  Favor/Favor/Sources/Scenes/Auth/Reactors/SignInViewReactor.swift
  Favor/Favor/Sources/Scenes/Auth/Reactors/SignUpViewReactor.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/SetProfileVC.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/SignInVC.swift
  Favor/Favor/Sources/Scenes/Profile/Common/Reactors/ProfileSectionHeaderReactor.swift
  Favor/Favor/Sources/Scenes/Profile/Common/ViewControllers/BaseProfileVC.swift
  Favor/Favor/Sources/Scenes/Profile/Common/Views/ProfileSectionHeader.swift
  Favor/Favor/Sources/Scenes/Profile/MyPage/Reactors/MyPageViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/MyPage/ViewControllers/EditMyPageVC.swift
  Favor/Favor/Sources/Scenes/Profile/MyPage/ViewControllers/MyPageVC.swift
  Favor/Favor/Sources/Scenes/Profile/ProfileSection.swift
  Favor/FavorKit/Sources/FavorKit/Components/Button/FavorSmallButton.swift
  Favor/FavorKit/Sources/FavorKit/Constants/ButtonType/FavorSmallButtonType.swift
  Favor/FavorKit/Sources/FavorKit/Extensions/Results+.swift
  Favor/FavorKit/Sources/FavorKit/Managers/RealmManager.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/User.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/User/UserAPI+Path.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/User/UserAPI+Task.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/DataMapping/ResponseDTO/UserResponseDTO.swift
Labels: ✨ New Feature
