Repository Favor-Gift-Reminder/Favor-iOS, pull requests merged in 2023-06, with the labels that each got.

#147 [Feat] 친구 페이지 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/FriendPageFlow.swift
  Favor/Favor/Sources/Flows/MyPageFlow.swift
  Favor/Favor/Sources/Scenes/Gift/VIewControllers/GiftVC.swift
  Favor/Favor/Sources/Scenes/MemoBottomSheet.swift
  Favor/Favor/Sources/Scenes/Popup/AlertPopup.swift
  Favor/Favor/Sources/Scenes/Profile/Common/ViewControllers/BaseProfileVC.swift
  Favor/Favor/Sources/Scenes/Profile/Common/Views/Cells/ProfileAnniversarySetupHelperCell.swift
  Favor/Favor/Sources/Scenes/Profile/Common/Views/Cells/ProfileMemoCell.swift
  Favor/Favor/Sources/Scenes/Profile/Common/Views/ProfileView.swift
  Favor/Favor/Sources/Scenes/Profile/FriendPage/Reactors/FriendPageViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/FriendPage/ViewControllers/FirendPageVC.swift
  Favor/Favor/Sources/Scenes/Profile/MyPage/Reactors/MyPageViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/ProfileSection.swift
  Favor/FavorKit/Sources/FavorKit/Base/BaseBottomSheet.swift
  Favor/FavorKit/Sources/FavorKit/Managers/RealmManager.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/Friend.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/DataMapping/ResponseDTO/FriendResponseDTO.swift
Labels: 🎨 UI

#154 [Refactor] Search 화면 DiffableDataSources 사용하는 것으로 리팩토링
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Favor/Favor.xcodeproj/xcshareddata/xcschemes/Favor.xcscheme
  Favor/Favor/Sources/Deprecated/.gitkeep
  Favor/Favor/Sources/Deprecated/UICollectionViewCompositionalLayout+.swift
  Favor/Favor/Sources/Flows/SearchFlow.swift
  Favor/Favor/Sources/Models/Storables/RecentSearch.swift
  Favor/Favor/Sources/Models/Storables/User.swift
  Favor/Favor/Sources/Scenes/Application/AppDelegate.swift
  Favor/Favor/Sources/Scenes/Auth/Reactors/SetProfileViewReactor.swift
  Favor/Favor/Sources/Scenes/FriendList/Reactors/BaseFriendListViewReactor.swift
  Favor/Favor/Sources/Scenes/Gift/GiftDetailSection.swift
  Favor/Favor/Sources/Scenes/Gift/Reactors/GiftDetailViewReactor.swift
  Favor/Favor/Sources/Scenes/GiftManagement/GiftManagementSection.swift
  Favor/Favor/Sources/Scenes/Home/Reactors/HomeViewReactor.swift
  Favor/Favor/Sources/Scenes/Home/ViewControllers/HomeVC.swift
  Favor/Favor/Sources/Scenes/Profile/FriendPage/Reactors/FriendPageViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/ProfileSection.swift
  Favor/Favor/Sources/Scenes/Search/Reactors/CellReactors/SearchGiftResultCellReactor.swift
  Favor/Favor/Sources/Scenes/Search/Reactors/CellReactors/SearchUserResultCellReactor.swift
  Favor/Favor/Sources/Scenes/Search/Reactors/SearchViewReactor.swift
  Favor/Favor/Sources/Scenes/Search/SearchRecentSection.swift
  Favor/Favor/Sources/Scenes/Search/SearchResultSection.swift
  Favor/Favor/Sources/Scenes/Search/SearchSection.swift
  Favor/Favor/Sources/Scenes/Search/ViewControllers/BaseSearchVC.swift
  Favor/Favor/Sources/Scenes/Search/ViewControllers/SearchResultVC.swift
  Favor/Favor/Sources/Scenes/Search/ViewControllers/SearchVC.swift
  Favor/Favor/Sources/Scenes/Search/Views/Cells/SearchGiftResultCell.swift
  Favor/Favor/Sources/Scenes/Search/Views/Cells/SearchRecentCell.swift
  Favor/Favor/Sources/Scenes/Search/Views/Cells/SearchUserResultCell.swift
  Favor/Favor/Sources/Scenes/Search/Views/SearchRecentHeader.swift
  Favor/FavorKit/Sources/FavorKit/Components/Button/FavorSmallButton.swift
  Favor/FavorKit/Sources/FavorKit/Constants/FavorCategory.swift
Labels: ♻️ Refactoring

#157 [Fix] 기념일 목록 분기처리
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Favor/Favor/Sources/Flows/AnniversaryFlow.swift
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/FriendPageFlow.swift
  Favor/Favor/Sources/Flows/MyPageFlow.swift
  Favor/Favor/Sources/Models/AnniversaryListType.swift
  Favor/Favor/Sources/Models/Storables/Anniversary.swift
  Favor/Favor/Sources/Models/Storables/Gift.swift
  Favor/Favor/Sources/Scenes/AnniversaryList/AnniversaryListSection.swift
  Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/AnniversaryListViewReactor.swift
  Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/BaseAnniversaryListViewReactor.swift
  Favor/Favor/Sources/Scenes/AnniversaryList/ViewControllers/AnniversaryListVC.swift
  Favor/Favor/Sources/Scenes/FriendList/Reactors/FriendListModifyingViewReactor.swift
  Favor/Favor/Sources/Scenes/Gift/GiftDetailSection.swift
  Favor/Favor/Sources/Scenes/Profile/FriendPage/Reactors/FriendPageViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/FriendPage/ViewControllers/FirendPageVC.swift
  Favor/Favor/Sources/Scenes/Profile/MyPage/Reactors/MyPageViewReactor.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/DataMapping/ResponseDTO/GiftResponseDTO.swift
Labels: 🎨 UI

#159 [Feat] 선물 상세 페이지 로직 연결
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/FriendPageFlow.swift
  Favor/Favor/Sources/Flows/GiftFlow.swift
  Favor/Favor/Sources/Flows/SearchFlow.swift
  Favor/Favor/Sources/Models/GiftTags.swift
  Favor/Favor/Sources/Models/Storables/Gift.swift
  Favor/Favor/Sources/Scenes/Friend/ViewControllers/FriendManagementVC.swift
  Favor/Favor/Sources/Scenes/Gift/GiftFriendsSection.swift
  Favor/Favor/Sources/Scenes/Gift/Reactors/GiftDetailViewReactor.swift
  Favor/Favor/Sources/Scenes/Gift/ViewControllers/GiftDetailVC.swift
  Favor/Favor/Sources/Scenes/Gift/ViewControllers/GiftFriendsBottomSheet.swift
  Favor/Favor/Sources/Scenes/Gift/Views/Cells/GiftDetailTagsCell.swift
  Favor/Favor/Sources/Scenes/Gift/Views/Cells/GiftFriendsBottomSheetCell.swift
  Favor/Favor/Sources/Scenes/GiftManagement/Reactors/GiftManagementViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/FriendPage/Reactors/FriendPageViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/FriendPage/ViewControllers/FirendPageVC.swift
  Favor/Favor/Sources/Scenes/Search/Reactors/SearchTagViewReactor.swift
  Favor/Favor/Sources/Scenes/Search/Reactors/SearchViewReactor.swift
  Favor/Favor/Sources/Scenes/Search/SearchTagSection.swift
  Favor/Favor/Sources/Scenes/Search/ViewControllers/BaseSearchTagVC.swift
  Favor/Favor/Sources/Scenes/Search/ViewControllers/SearchCategoryVC.swift
  Favor/Favor/Sources/Scenes/Search/ViewControllers/SearchEmotionVC.swift
  Favor/Favor/Sources/Scenes/Search/ViewControllers/SearchVC.swift
  Favor/Favor/Sources/Scenes/Search/Views/Cells/SearchRecentCell.swift
  Favor/FavorKit/Sources/FavorKit/Base/BaseBottomSheet.swift
  Favor/FavorKit/Sources/FavorKit/Components/Button/FavorEmotionButton.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorProfileImageRegisterButton.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorProfileImageView.swift
  Favor/FavorKit/Sources/FavorKit/Constants/FavorEmotion.swift
  Favor/FavorKit/Sources/FavorKit/Managers/Realm/Realm+Transaction.swift
  Favor/FavorKit/Sources/FavorKit/Models/RecentSearchObject.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/GiftObject.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/DataMapping/RequestDTO/Gift/GiftRequestDTO.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/DataMapping/RequestDTO/Gift/GiftUpdateRequestDTO.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/DataMapping/ResponseDTO/GiftResponseDTO.swift
Labels: ✨ New Feature

#166 [Feat] 추가 UI 수정 및 구현(1)
  Favor/Favor/Assets/Assets.xcassets/Icon/ic_error.imageset/Contents.json
  Favor/Favor/Assets/Assets.xcassets/Icon/ic_error.imageset/ic_error.svg
  Favor/Favor/Sources/Flows/AnniversaryFlow.swift
  Favor/Favor/Sources/Flows/FriendFlow.swift
  Favor/Favor/Sources/Flows/FriendListFlow.swift
  Favor/Favor/Sources/Flows/FriendPageFlow.swift
  Favor/Favor/Sources/Flows/GiftFlow.swift
  Favor/Favor/Sources/Flows/MyPageFlow.swift
  Favor/Favor/Sources/Flows/NewGiftFlow.swift
  Favor/Favor/Sources/Flows/ReminderFlow.swift
  Favor/Favor/Sources/Flows/SearchFlow.swift
  Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/AnniversaryListViewReactor.swift
  Favor/Favor/Sources/Scenes/AnniversaryList/ViewControllers/AnniversaryListModifyingVC.swift
  Favor/Favor/Sources/Scenes/AnniversaryList/ViewControllers/AnniversaryListVC.swift
  Favor/Favor/Sources/Scenes/Dashboard/ViewControllers/FavorTabBarController.swift
  Favor/Favor/Sources/Scenes/FriendList/ViewControllers/BaseFriendListVC.swift
  Favor/Favor/Sources/Scenes/FriendList/Views/Cells/BaseFriendCell.swift
  Favor/Favor/Sources/Scenes/FriendList/Views/Cells/FriendListCell.swift
  Favor/Favor/Sources/Scenes/Gift/ViewControllers/GiftDetailVC.swift
  Favor/Favor/Sources/Scenes/Gift/Views/Cells/GiftFriendsBottomSheetCell.swift
  Favor/Favor/Sources/Scenes/Profile/Common/ViewControllers/BaseProfileVC.swift
  Favor/Favor/Sources/Scenes/Profile/Common/Views/Cells/ProfileFriendCell.swift
  Favor/Favor/Sources/Scenes/Profile/Common/Views/ProfileView.swift
  Favor/Favor/Sources/Scenes/Profile/FriendPage/ViewControllers/FirendPageVC.swift
  Favor/Favor/Sources/Scenes/Profile/MyPage/Reactors/MyPageViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/MyPage/ViewControllers/MyPageVC.swift
  Favor/Favor/Sources/Scenes/Reminder/ViewControllers/ReminderVC.swift
  Favor/FavorKit/Sources/FavorKit/Base/BaseFriendCell.swift
  Favor/FavorKit/Sources/FavorKit/Base/BaseNavigationController.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorProfilePhotoView.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorToastMessageView/FavorToastMessageView.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorToastMessageView/Protocols/UIViewController+Toastable.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorToastMessageView/ToastMessage.swift
  Favor/FavorKit/Sources/FavorKit/Extensions/UIColor+.swift
  Favor/FavorKit/Sources/FavorKit/Extensions/UIImage+.swift
  Favor/FavorKit/Sources/FavorKit/Managers/ToastManager.swift
Labels: 🎨 UI

#169 [Feat] 이메일 Auth / 액세스 토큰 적용
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Favor/Favor/Assets/Assets.xcassets/Icon/ic_favor.imageset/Contents.json
  Favor/Favor/Base.lproj/LaunchScreen.storyboard
  Favor/Favor/Info.plist
  Favor/Favor/Sources/Flows/AppFlow.swift
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/AppStepper.swift
  Favor/Favor/Sources/Flows/AppStpper.swift
  Favor/Favor/Sources/Flows/AuthFlow.swift
  Favor/Favor/Sources/Flows/DashboardFlow.swift
  Favor/Favor/Sources/Flows/GiftFlow.swift
  Favor/Favor/Sources/Flows/NewGiftFlow.swift
  Favor/Favor/Sources/Flows/ReminderFlow.swift
  Favor/Favor/Sources/Scenes/Application/AppDelegate.swift
  Favor/Favor/Sources/Scenes/Application/SceneDelegate.swift
  Favor/Favor/Sources/Scenes/Auth/SignIn/Reactors/AuthSignInViewReactor.swift
  Favor/Favor/Sources/Scenes/Auth/SignIn/ViewControllers/AuthEntryVC.swift
  Favor/Favor/Sources/Scenes/Auth/SignIn/ViewControllers/AuthSignInVC.swift
  Favor/Favor/Sources/Scenes/Auth/SignIn/Views/SocialAuthButton.swift
  Favor/Favor/Sources/Scenes/Auth/SignUp/Reactors/AuthSignUpViewReactor.swift
  Favor/Favor/Sources/Scenes/Auth/Term/Reactors/AuthTermViewReactor.swift
  Favor/Favor/Sources/Scenes/Home/Reactors/HomeViewReactor.swift
  Favor/Favor/Sources/Scenes/Splash/Reactors/SplashViewReactor.swift
  Favor/Favor/Sources/Scenes/Splash/SplashVC.swift
  Favor/Favor/Sources/Scenes/Splash/ViewControllers/SplashVC.swift
  Favor/FavorKit/Sources/FavorKit/Constants/AuthState.swift
  Favor/FavorKit/Sources/FavorKit/Constants/UserDefaultsKey.swift
  Favor/FavorKit/Sources/FavorKit/Extensions/UIColor+.swift
  Favor/FavorKit/Sources/FavorKit/Managers/Keychain/Keychain+Constants.swift
  Favor/FavorKit/Sources/FavorKit/Managers/Keychain/Keychain+Transactions.swift
  Favor/FavorKit/Sources/FavorKit/Storages/FTUXStorage.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIError.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIManager.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/User/UserAPI.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/BaseTargetType.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/DataMapping/ResponseDTO/ErrorResponseDTO.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/Networking+Plugin.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/Networking+Request.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/Networking.swift
Labels: ✨ New Feature, ♻️ Refactoring

#171 [Feat] 추가 UI 수정 및 구현(2)
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Assets/Assets.xcassets/Icon/ic_pick.imageset/Contents.json
  Favor/Favor/Assets/Assets.xcassets/Icon/ic_pick.imageset/Icon_pick.svg
  Favor/Favor/Assets/Assets.xcassets/Icon/ic_pick.imageset/ic_pick.pdf
  Favor/Favor/Sources/Flows/AnniversaryFlow.swift
  Favor/Favor/Sources/Flows/MyPageFlow.swift
  Favor/Favor/Sources/Scenes/Anniversary/AnniversaryManagementSection.swift
  Favor/Favor/Sources/Scenes/Anniversary/Reactors/AnniversaryManagementViewReactor.swift
  Favor/Favor/Sources/Scenes/Anniversary/ViewControllers/AnniversaryManagementVC.swift
  Favor/Favor/Sources/Scenes/AnniversaryBottomSheet.swift
  Favor/Favor/Sources/Scenes/AnniversaryList/ViewControllers/AnniversaryListVC.swift
  Favor/Favor/Sources/Scenes/FriendList/Reactors/FriendListModifyingViewReactor.swift
  Favor/Favor/Sources/Scenes/FriendList/ViewControllers/FriendListModifyingVC.swift
  Favor/Favor/Sources/Scenes/Popup/ViewControllers/AlertPopup.swift
  Favor/Favor/Sources/Scenes/Popup/ViewControllers/BasePopup.swift
  Favor/Favor/Sources/Scenes/Popup/ViewControllers/ReminderDatePopup.swift
  Favor/Favor/Sources/Scenes/Profile/Common/ViewControllers/BaseProfileVC.swift
  Favor/Favor/Sources/Scenes/Profile/Common/Views/Cells/ProfileSetupHelperCell.swift
  Favor/Favor/Sources/Scenes/Profile/EditMyPage/EditMyPageSection.swift
  Favor/Favor/Sources/Scenes/Profile/EditMyPage/Views/Cells/EditMyPageFavorCell.swift
  Favor/Favor/Sources/Scenes/Profile/MyPage/Reactors/MyPageViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/MyPage/ViewControllers/MyPageVC.swift
  Favor/Favor/Sources/Scenes/Reminder/ViewControllers/ReminderVC.swift
  Favor/FavorKit/Sources/FavorKit/Components/CollectionView/Cells/FavorSelectorCell.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorDatePickerTextField.swift
Labels: 🎨 UI
