Repository Favor-Gift-Reminder/Favor-iOS, pull requests merged in 2023-01, with the labels that each got.

#9 [ADD] Configuration을 사용한 UIButton 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Configuration/Constants/.gitkeep
  Favor/Favor/Configuration/Constants/FavorStyle.swift
  Favor/Favor/Configuration/Extensions/UIButton+.swift
  Favor/Favor/Configuration/Extensions/UIColor+.swift
Labels: ✨ New Feature

#10 [FEAT] 프로젝트 디렉토리 설정
  .gitignore
  Favor/.swiftlint.yml
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/AppDelegate.swift
  Favor/Favor/Base.lproj/LaunchScreen.storyboard
  Favor/Favor/Configuration/Assets/Assets.xcassets/AccentColor.colorset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/Contents.json
  Favor/Favor/Configuration/Base/BaseCoordinator.swift
  Favor/Favor/Configuration/Base/BaseViewController.swift
  Favor/Favor/Configuration/Base/Coordinator.swift
  Favor/Favor/Configuration/Constants/FavorStyle.swift
  Favor/Favor/Configuration/Extensions/README.md
  Favor/Favor/Configuration/Extensions/UIButton+.swift
  Favor/Favor/Configuration/Extensions/UIColor+.swift
  Favor/Favor/Configuration/Fonts/.gitkeep
  Favor/Favor/SceneDelegate.swift
  Favor/Favor/Sources/Models/.gitkeep
  Favor/Favor/Sources/Network/DataMapping/README.md
  Favor/Favor/Sources/Scenes/Application/AppCoordinator.swift
  Favor/Favor/Sources/Scenes/Application/AppDelegate.swift
  Favor/Favor/Sources/Scenes/Application/SceneDelegate.swift
  Favor/Favor/Sources/Scenes/Application/Splash/SplashReactor.swift
  Favor/Favor/Sources/Scenes/Application/Splash/SplashVC.swift
  Favor/Favor/Sources/Scenes/Application/TabBar/TabBarCoordinator.swift
  Favor/Favor/Sources/Scenes/Application/TabBar/TabBarPage.swift
  Favor/Favor/Sources/Scenes/Auth/AuthCoordinator.swift
  Favor/Favor/Sources/Scenes/Auth/AuthReactor.swift
  Favor/Favor/Sources/Scenes/Gift/Reactor/.gitkeep
  Favor/Favor/Sources/Scenes/Gift/ViewControllers/GiftVC.swift
  Favor/Favor/Sources/Scenes/Gift/ViewControllers/ShareVC.swift
  Favor/Favor/Sources/Scenes/Gift/Views/.gitkeep
  Favor/Favor/Sources/Scenes/Home/Home/Coordinator/HomeCoordinator.swift
  Favor/Favor/Sources/Scenes/Home/Home/Reactor/HomeReactor.swift
  Favor/Favor/Sources/Scenes/Home/Home/ViewControllers/HomeVC.swift
  Favor/Favor/Sources/Scenes/Home/Home/Views/.gitkeep
  Favor/Favor/Sources/Scenes/Home/NewGift/Coordinator/NewGiftCoordinator.swift
  Favor/Favor/Sources/Scenes/Home/NewGift/ViewControllers/.gitkeep
  Favor/Favor/Sources/Scenes/Home/Search/Coordinator/SearchCoordinator.swift
  Favor/Favor/Sources/Scenes/Home/Search/ViewControllers/.gitkeep
  Favor/Favor/Sources/Scenes/MyPage/Coordinator/MyPageCoordinator.swift
  Favor/Favor/Sources/Scenes/MyPage/Reactor/.gitkeep
  Favor/Favor/Sources/Scenes/MyPage/ViewControllers/MyPageVC.swift
  Favor/Favor/Sources/Scenes/MyPage/ViewControllers/SettingVC.swift
  Favor/Favor/Sources/Scenes/MyPage/Views/.gitkeep
  Favor/Favor/Sources/Scenes/Onboard/OnboardVC.swift
  Favor/Favor/Sources/Scenes/Reminder/Coordinator/ReminderCoordinator.swift
  Favor/Favor/Sources/Scenes/Reminder/Reactor/.gitkeep
  Favor/Favor/Sources/Scenes/Reminder/ViewControllers/EventEditVC.swift
  Favor/Favor/Sources/Scenes/Reminder/ViewControllers/EventVC.swift
  Favor/Favor/Sources/Scenes/Reminder/ViewControllers/ReminderVC.swift
  Favor/Favor/Sources/Scenes/Reminder/Views/.gitkeep
  Favor/Favor/ViewController.swift
  README.md
Labels: 🛠️ Project Setup

#12 [FEAT] UIButton Configuration 구현
  .github/workflows/build.yml
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Configuration/Base/UIFactory.swift
  Favor/Favor/Configuration/Extensions/UIButton+.swift
Labels: ✨ New Feature

#13 [ADD] UIButton 적용 사항 fetch
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yml
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Configuration/Base/UIFactory.swift
  Favor/Favor/Configuration/Extensions/UIButton+.swift
Labels: 🏎️ Fetch

#18 [Feat] Onboarding UI 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Configuration/Base/BaseView.swift
  Favor/Favor/Configuration/Base/UIFactory.swift
  Favor/Favor/Configuration/Extensions/Preview.swift
  Favor/Favor/Sources/Scenes/Onboard/OnboardVC.swift
  Favor/Favor/Sources/Scenes/Onboarding/OnboardingCell.swift
  Favor/Favor/Sources/Scenes/Onboarding/OnboardingSlide.swift
  Favor/Favor/Sources/Scenes/Onboarding/OnboardingVC.swift
Labels: 🎨 UI

#20 [FEAT] BaseTextField 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Configuration/Base/FavorTextField.swift
Labels: ✨ New Feature, 🎨 UI

#21 [Feat] Pretendard 폰트 추가 및 UIFont+ 전역 메서드 추가
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Configuration/Assets/Pretendard-Bold.otf
  Favor/Favor/Configuration/Assets/Pretendard-Regular.otf
  Favor/Favor/Configuration/Extensions/UIFont+.swift
  Favor/Favor/Info.plist
Labels: ✨ New Feature

#25 [REFACTOR] FavorColor UIColor extension으로 변경
  Favor/Favor/Configuration/Extensions/UIColor+.swift
Labels: ♻️ Refactoring

#34 [Feat] PlainFavorButton 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_bottomArrow.imageset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_bottomArrow.imageset/Wire_Icon_화살표4.png
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_bottomArrow.imageset/Wire_Icon_화살표4@2x.png
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_bottomArrow.imageset/Wire_Icon_화살표4@3x.png
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_rightArrow.imageset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_rightArrow.imageset/keyboard_arrow_right.png
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_rightArrow.imageset/keyboard_arrow_right@2x.png
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_rightArrow.imageset/keyboard_arrow_right@3x.png
  Favor/Favor/Configuration/Base/BaseCoordinator.swift
  Favor/Favor/Configuration/Views/PlainFavorButton.swift
Labels: 🎨 UI

#37 [Feat] PlainFavorButton 구현(2)
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_bottomArrow.imageset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_bottomArrow.imageset/Wire_Icon_화살표4.png
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_bottomArrow.imageset/Wire_Icon_화살표4@2x.png
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_bottomArrow.imageset/Wire_Icon_화살표4@3x.png
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_rightArrow.imageset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_rightArrow.imageset/keyboard_arrow_right.png
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_rightArrow.imageset/keyboard_arrow_right@2x.png
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_rightArrow.imageset/keyboard_arrow_right@3x.png
  Favor/Favor/Configuration/Views/PlainFavorButton.swift
Labels: 🎨 UI

#39 [Feat] 전역적 UINavigationBarAppearance 구현
  Favor/Favor/Sources/Scenes/Application/SceneDelegate.swift
Labels: 🎨 UI

#32 [FEAT] 회원가입 UI 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor.xcodeproj/xcshareddata/xcschemes/Favor.xcscheme
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_add.imageset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_add.imageset/ic_add.svg
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_eye.imageset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_eye.imageset/ic_eye.svg
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_eye_closed.imageset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_eye_closed.imageset/ic_eye_closed.svg
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_eye_closed_small.imageset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_eye_closed_small.imageset/ic_eye_closed_small.svg
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_eye_small.imageset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_eye_small.imageset/ic_eye_small.svg
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_person.imageset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_person.imageset/ic_person.svg
  Favor/Favor/Configuration/Base/BaseViewController.swift
  Favor/Favor/Configuration/Utils/CoreGraphicManager.swift
  Favor/Favor/Configuration/Utils/PHPickerManager.swift
  Favor/Favor/Configuration/Utils/ValidateManager.swift
  Favor/Favor/Configuration/Views/FavorTextField.swift
  Favor/Favor/Configuration/Views/LargeFavorButton.swift
  Favor/Favor/Sources/Scenes/Application/AppCoordinator.swift
  Favor/Favor/Sources/Scenes/Auth/AuthCoordinator.swift
  Favor/Favor/Sources/Scenes/Auth/AuthReactor.swift
  Favor/Favor/Sources/Scenes/Auth/Coordinator/AuthCoordinator.swift
  Favor/Favor/Sources/Scenes/Auth/Reactor/SelectSignInReactor.swift
  Favor/Favor/Sources/Scenes/Auth/Reactor/SetProfileReactor.swift
  Favor/Favor/Sources/Scenes/Auth/Reactor/SignInReactor.swift
  Favor/Favor/Sources/Scenes/Auth/Reactor/SignUpReactor.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/SelectSignInVC.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/SetProfileVC.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/SignInVC.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/SignUpVC.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/TermVC.swift
  Favor/FavorUITests/FavorUITests.swift
  Favor/FavorUITests/FavorUITestsLaunchTests.swift
Labels: 🎨 UI

#42 [Feat] Onboarding UI 구현 (2)
  Favor/Favor/Configuration/Utils/UpdateHandlerManager.swift
  Favor/Favor/Sources/Scenes/Application/AppCoordinator.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/SelectSignInVC.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/SignInVC.swift
  Favor/Favor/Sources/Scenes/Onboarding/OnboardingCell.swift
  Favor/Favor/Sources/Scenes/Onboarding/OnboardingVC.swift
Labels: 🎨 UI

#44 [Feat] FavorTabBarController 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_home.imageset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_home.imageset/ic_home.svg
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_notification.imageset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_notification.imageset/ic_notification.svg
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_person_circle.imageset/Contents.json
  Favor/Favor/Configuration/Assets/Assets.xcassets/ic_person_circle.imageset/ic_person_circle.svg
  Favor/Favor/Configuration/Base/BaseCoordinator.swift
  Favor/Favor/Configuration/Base/Coordinator.swift
  Favor/Favor/Configuration/Base/Delegate/CoordinatorFinishDelegate.swift
  Favor/Favor/Configuration/Views/FavorTextField.swift
  Favor/Favor/Sources/Scenes/Application/AppCoordinator.swift
  Favor/Favor/Sources/Scenes/Application/AppDelegate.swift
  Favor/Favor/Sources/Scenes/Application/SceneDelegate.swift
  Favor/Favor/Sources/Scenes/Application/TabBar/TabBarController.swift
  Favor/Favor/Sources/Scenes/Application/TabBar/TabBarCoordinator.swift
  Favor/Favor/Sources/Scenes/Application/TabBar/TabBarPage.swift
  Favor/Favor/Sources/Scenes/Auth/Coordinator/AuthCoordinator.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/SetProfileVC.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/TermVC.swift
Labels: ✨ New Feature, 🎨 UI

#45 [Refactor] AuthFlow 초입 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Favor/Favor/Sources/Scenes/Application/AppCoordinator.swift
  Favor/Favor/Sources/Scenes/Application/Flows/AppFlow.swift
  Favor/Favor/Sources/Scenes/Application/Flows/AppStep.swift
  Favor/Favor/Sources/Scenes/Application/Flows/AppStepper.swift
  Favor/Favor/Sources/Scenes/Application/SceneDelegate.swift
  Favor/Favor/Sources/Scenes/Application/Splash/SplashReactor.swift
  Favor/Favor/Sources/Scenes/Application/Splash/SplashVC.swift
  Favor/Favor/Sources/Scenes/Auth/Coordinator/AuthCoordinator.swift
  Favor/Favor/Sources/Scenes/Auth/Flows/AuthFlow.swift
  Favor/Favor/Sources/Scenes/Auth/Flows/AuthStep.swift
  Favor/Favor/Sources/Scenes/Auth/Reactor/SelectSignInReactor.swift
  Favor/Favor/Sources/Scenes/Auth/Reactor/SetProfileReactor.swift
  Favor/Favor/Sources/Scenes/Auth/Reactor/SignInReactor.swift
  Favor/Favor/Sources/Scenes/Auth/Reactor/SignUpReactor.swift
  Favor/Favor/Sources/Scenes/Auth/ViewControllers/TermVC.swift
  Favor/Favor/Sources/Scenes/Home/Home/Views/.gitkeep
Labels: ♻️ Refactoring
