Repository Favor-Gift-Reminder/Favor-iOS, pull requests merged in 2023-07, with the labels that each got.

#174 [Hotfix] 서버 재배포 이후 API 수정
  Favor/Favor/Sources/Scenes/Anniversary/Reactors/AnniversaryManagementViewReactor.swift
  Favor/Favor/Sources/Scenes/AnniversaryList/Reactors/BaseAnniversaryListViewReactor.swift
  Favor/Favor/Sources/Scenes/Auth/Profile/Reactors/AuthSetProfileViewReactor.swift
  Favor/Favor/Sources/Scenes/Auth/SignIn/Reactors/AuthSignInViewReactor.swift
  Favor/Favor/Sources/Scenes/FriendList/Reactors/BaseFriendListViewReactor.swift
  Favor/Favor/Sources/Scenes/GiftManagement/Reactors/GiftManagementViewReactor.swift
  Favor/Favor/Sources/Scenes/GiftManagement/Reactors/NewGiftFriendViewReactor.swift
  Favor/Favor/Sources/Scenes/Home/Reactors/HomeViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/EditMyPage/Reactors/EditMyPageViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/FriendPage/Reactors/FriendPageViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/MyPage/Reactors/MyPageViewReactor.swift
  Favor/Favor/Sources/Scenes/Reminder/Reactor/ReminderViewReactor.swift
  Favor/Favor/Sources/Scenes/Search/Reactors/SearchTagViewReactor.swift
  Favor/Favor/Sources/Scenes/Search/Reactors/SearchViewReactor.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Anniversary/AnniversaryAPI+Method.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Anniversary/AnniversaryAPI+Path.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Anniversary/AnniversaryAPI+Task.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Anniversary/AnniversaryAPI.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Friend/FriendAPI+Method.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Friend/FriendAPI+Path.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Friend/FriendAPI+Task.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Friend/FriendAPI.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Gift/GiftAPI+Method.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Gift/GiftAPI+Path.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Gift/GiftAPI+Task.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Gift/GiftAPI.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Reminder/ReminderAPI+Method.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Reminder/ReminderAPI+Path.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Reminder/ReminderAPI+Task.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/Reminder/ReminderAPI.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/User/UserAPI+Method.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/User/UserAPI+Path.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/User/UserAPI+Task.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/APIs/User/UserAPI.swift
Labels: ♻️ Refactoring

#177 [Feat] 네트워크 에러 핸들링 구현
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Sources/Scenes/Application/AppDelegate.swift
  Favor/FavorKit/Sources/FavorKit/Base/BasePopup.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorPopup.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorToastMessageView/ToastMessage.swift
  Favor/FavorKit/Sources/FavorKit/Extensions/UIApplication+.swift
  Favor/FavorKit/Sources/FavorKit/Managers/FavorNotificationManager.swift
  Favor/FavorKit/Sources/FavorKit/Managers/NetworkCheckManager.swift
  Favor/FavorKit/Sources/FavorKit/Managers/ToastManager.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/DataMapping/ResponseDTO/ErrorResponseDTO.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/Networking/Networking+NetworkError.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/Networking/Networking+Plugin.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/Networking/Networking+Request.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/Networking/Networking.swift
Labels: ✨ New Feature, 🎨 UI

#180 [Feat] ImageCache 및 PHPicker 구현
  .github/secrets/Certificates.p12.gpg
  .github/secrets/FavorAppleDevelopmentProvision.mobileprovision.gpg
  .github/workflows/build.yml
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/AuthFlow.swift
  Favor/Favor/Sources/Flows/GiftFlow.swift
  Favor/Favor/Sources/Flows/MyPageFlow.swift
  Favor/Favor/Sources/Flows/NewGiftFlow.swift
  Favor/Favor/Sources/Models/Storables/Friend.swift
  Favor/Favor/Sources/Models/Storables/Gift.swift
  Favor/Favor/Sources/Models/Storables/Photo.swift
  Favor/Favor/Sources/Models/Storables/User.swift
  Favor/Favor/Sources/Scenes/Anniversary/ViewControllers/AnniversaryManagementVC.swift
  Favor/Favor/Sources/Scenes/Auth/Profile/Reactors/AuthSetProfileViewReactor.swift
  Favor/Favor/Sources/Scenes/GiftManagement/Reactors/GiftManagementViewReactor.swift
  Favor/Favor/Sources/Scenes/GiftManagement/VIewControllers/GiftManagementVC.swift
  Favor/Favor/Sources/Scenes/Home/Views/Cells/HomeTimelineCell.swift
  Favor/Favor/Sources/Scenes/Profile/Common/ViewControllers/BaseProfileVC.swift
  Favor/Favor/Sources/Scenes/Profile/Common/Views/ProfileView.swift
  Favor/Favor/Sources/Scenes/Profile/EditMyPage/Reactors/EditMyPageViewReactor.swift
  Favor/Favor/Sources/Scenes/Profile/EditMyPage/ViewControllers/EditMyPageVC.swift
  Favor/Favor/Sources/Scenes/Profile/EditMyPage/Views/EditMyPageCollectionHeaderView.swift
  Favor/Favor/Sources/Scenes/Profile/EditMyPage/Views/EditMyPageProfileHeader.swift
  Favor/Favor/Sources/Scenes/Profile/MyPage/ViewControllers/MyPageVC.swift
  Favor/FavorKit/Sources/FavorKit/Base/BaseNavigationController.swift
  Favor/FavorKit/Sources/FavorKit/Components/CollectionView/Cells/FavorTextFieldCell.swift
  Favor/FavorKit/Sources/FavorKit/Managers/ImageCache/ImageCache+CacheKeyMapper.swift
  Favor/FavorKit/Sources/FavorKit/Managers/ImageCache/ImageCache+Manager.swift
  Favor/FavorKit/Sources/FavorKit/Managers/ImageCache/UIImageView+ImageCache.swift
  Favor/FavorKit/Sources/FavorKit/Managers/PHPickerManager.swift
  Favor/FavorKit/Sources/FavorKit/Managers/Realm/Realm+Migration.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/FriendObject.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/GiftObject.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/Photo.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/PhotoObject.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/UserObject.swift
Labels: ✨ New Feature, ♻️ Refactoring

#181 [Feat] ReminderBusniessLogic
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor/Sources/Flows/AppStep.swift
  Favor/Favor/Sources/Flows/GiftFlow.swift
  Favor/Favor/Sources/Flows/NewGiftFlow.swift
  Favor/Favor/Sources/Flows/ReminderFlow.swift
  Favor/Favor/Sources/Models/Storables/Friend.swift
  Favor/Favor/Sources/Models/Storables/Reminder.swift
  Favor/Favor/Sources/Scenes/Friend/ViewControllers/FriendSelectionVC.swift
  Favor/Favor/Sources/Scenes/FriendList/ViewControllers/BaseFriendListVC.swift
  Favor/Favor/Sources/Scenes/FriendList/ViewControllers/FriendListVC.swift
  Favor/Favor/Sources/Scenes/GiftManagement/Reactors/CellReactros/NewGiftFriendCellReactor.swift
  Favor/Favor/Sources/Scenes/GiftManagement/Reactors/FriendSelectorViewReactor.swift
  Favor/Favor/Sources/Scenes/GiftManagement/Views/Cells/FriendSelectorCell.swift
  Favor/Favor/Sources/Scenes/GiftManagement/Views/Cells/FriendSelectorEmptyCell.swift
  Favor/Favor/Sources/Scenes/GiftManagement/Views/FriendSelectorFooterView.swift
  Favor/Favor/Sources/Scenes/GiftManagement/Views/FriendSelectorHeaderView.swift
  Favor/Favor/Sources/Scenes/Reminder/Reactor/ReminderEditViewReactor.swift
  Favor/Favor/Sources/Scenes/Reminder/Reactor/ReminderViewReactor.swift
  Favor/Favor/Sources/Scenes/Reminder/ViewControllers/BaseReminderVC.swift
  Favor/Favor/Sources/Scenes/Reminder/ViewControllers/ReminderEditVC.swift
  Favor/Favor/Sources/Scenes/Reminder/ViewControllers/ReminderVC.swift
  Favor/FavorKit/Sources/FavorKit/Base/BasePopup.swift
  Favor/FavorKit/Sources/FavorKit/Components/Button/Constants/FavorPlainButtonType.swift
  Favor/FavorKit/Sources/FavorKit/Components/Button/FavorPlainButton.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorDatePickerTextField.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorTextField.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorToastMessageView/ToastMessage.swift
  Favor/FavorKit/Sources/FavorKit/Constants/NotifyDays.swift
  Favor/FavorKit/Sources/FavorKit/Extensions/Date+.swift
  Favor/FavorKit/Sources/FavorKit/Managers/AuthValidationManager.swift
  Favor/FavorKit/Sources/FavorKit/Managers/Realm/Realm+Workbench.swift
  Favor/FavorKit/Sources/FavorKit/Models/Remote/ReminderObject.swift
Labels: 🧹 Clean Up, ✨ New Feature

#183 [TEST] Home Logic
  Favor/Favor.xcodeproj/project.pbxproj
  Favor/Favor.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Favor/Favor/Sources/Flows/AppFlow.swift
  Favor/Favor/Sources/Flows/DashboardFlow.swift
  Favor/Favor/Sources/Flows/HomeFlow.swift
  Favor/Favor/Sources/Flows/NewGiftFlow.swift
  Favor/Favor/Sources/Models/Storables/Reminder.swift
  Favor/Favor/Sources/Scenes/Dashboard/ViewControllers/FavorTabBarController.swift
  Favor/Favor/Sources/Scenes/Dashboard/Views/FavorTabBar.swift
  Favor/Favor/Sources/Scenes/FilterBottomSheet.swift
  Favor/Favor/Sources/Scenes/Gift/Reactors/GiftDetailViewReactor.swift
  Favor/Favor/Sources/Scenes/Gift/ViewControllers/GiftDetailVC.swift
  Favor/Favor/Sources/Scenes/Gift/Views/Cells/GiftDetailTitleCell.swift
  Favor/Favor/Sources/Scenes/Home/HomeSection.swift
  Favor/Favor/Sources/Scenes/Home/Reactors/HomeViewReactor.swift
  Favor/Favor/Sources/Scenes/Home/ViewControllers/HomeVC.swift
  Favor/Favor/Sources/Scenes/Home/Views/Cells/HomeTimelineCell.swift
  Favor/Favor/Sources/Scenes/Home/Views/HomeHeaderView.swift
  Favor/FavorKit/Sources/FavorKit/Managers/Realm/Realm+Transaction.swift
  Favor/FavorKit/Sources/FavorKit/Managers/Realm/Realm+Workbench.swift
Labels: 🐞 Bug

#185 [Test] Gift
  Favor/Favor/Sources/Flows/AppFlow.swift
  Favor/Favor/Sources/Flows/GiftFlow.swift
  Favor/Favor/Sources/Flows/HomeFlow.swift
  Favor/Favor/Sources/Flows/NewGiftFlow.swift
  Favor/Favor/Sources/Scenes/Dashboard/Views/FavorTabBar.swift
  Favor/Favor/Sources/Scenes/Gift/ViewControllers/GiftDetailVC.swift
  Favor/Favor/Sources/Scenes/GiftManagement/Reactors/GiftManagementViewReactor.swift
  Favor/Favor/Sources/Scenes/GiftManagement/VIewControllers/GiftManagementVC.swift
  Favor/Favor/Sources/Scenes/Home/ViewControllers/HomeVC.swift
  Favor/Favor/Sources/Scenes/Home/Views/Cells/HomeTimelineCell.swift
  Favor/Favor/Sources/Scenes/Popup/ViewControllers/NewAlertPopup.swift
  Favor/Favor/Sources/Scenes/Search/Views/Cells/SearchGiftResultCell.swift
  Favor/FavorKit/Sources/FavorKit/Base/BasePopup.swift
  Favor/FavorKit/Sources/FavorKit/Components/FavorToastMessageView/ToastMessage.swift
  Favor/FavorNetworkKit/Sources/FavorNetworkKit/DataMapping/ResponseDTO/GiftResponseDTO.swift
Labels: 🐞 Bug
